name: Run tests

on: [ push, pull_request ]

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

      - name: Run go tests
        run: go test ./...
